#PBS -q class
#PBS -l nodes=1
#PBS -l walltime=00:01:00
#PBS -N qsort

# Changes to the directory we were in when we
# submit the job:

cd $PBS_O_WORKDIR

# Runs a bunch of standard command-line
# utilities, just as an example:

echo "Script began:" `date`
echo "Node:" `hostname`
echo "Current directory: ${PWD}"

echo ""
echo "=== Running Quicksort on 10 million elements ... ==="
./qsort 10000000

echo ""
echo "=== Done! ==="

# eof
